// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"gin-vue-template/config"
	"gin-vue-template/pkg/infra/redis"
	"gin-vue-template/pkg/logic"
	"gin-vue-template/pkg/models"
	"gin-vue-template/pkg/service"
	"gin-vue-template/routers"
	"gin-vue-template/routers/api"
	"gin-vue-template/routers/middleware"
)

// Injectors from wire.go:

func InitializeService() *service.Service {
	configConfig := config.NewConfig()
	prefixRedisClient := redis.NewRedisClient(configConfig)
	gormDAO := models.NewDAO(configConfig)
	logicLogic := logic.NewLogic(prefixRedisClient, gormDAO)
	middlewareMiddleware := middleware.NewMiddleware(logicLogic)
	apiAPI := api.NewAPI(logicLogic, gormDAO)
	engine := routers.NewRouter(configConfig, middlewareMiddleware, apiAPI)
	server := service.NewHTTPServer(engine, configConfig)
	serviceService := &service.Service{
		HTTPServer: server,
	}
	return serviceService
}
